/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author glen macdonald
 * @date 27-May-2022
 * @Description - Calculates 
 */
public class Cafe extends javax.swing.JFrame {
    private int numberOfCoffees = 0;
    private final double costLatte = 4.5;
    private final int costMocca = 5;
    private final int costShortBlack = 3;
    private double costTotal = 0.0;
    private double costCoffee;
    
    
    /**
     * Creates new form Cafe
     */
    public Cafe() {
        initComponents();
    }

    private int getNumberOfCoffees() {
        try {
            return Integer.parseInt(txtNumberCoffees.getText());
        } catch (Exception ex) {
            txtTotalCost.setText("Number of Coffees needs to be an Integer");
            return 0;
        }
    }
    
    private void setTotalCost(double totalCost) {
        txtTotalCost.setText("$" + Double.toString(totalCost));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCoffees = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        txtNumberCoffees = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLatte = new javax.swing.JRadioButton();
        btnMocca = new javax.swing.JRadioButton();
        btnShortBlack = new javax.swing.JRadioButton();
        btnCalculate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotalCost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Abner Britto's Cafe");

        lblNumber.setText("Number of coffees:");

        txtNumberCoffees.setToolTipText("Enter number of Coffees here");
        txtNumberCoffees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberCoffeesActionPerformed(evt);
            }
        });

        jLabel1.setText("Types of coffee:");

        btnCoffees.add(btnLatte);
        btnLatte.setText("Latte $4.50");
        btnLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatteActionPerformed(evt);
            }
        });

        btnCoffees.add(btnMocca);
        btnMocca.setText("Mocca $5.00");

        btnCoffees.add(btnShortBlack);
        btnShortBlack.setText("Short Black $3.00");

        btnCalculate.setText("Calculate Cost");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Cost:");

        txtTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnCalculate)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNumberCoffees))
                                .addComponent(lblTitle))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnShortBlack)
                            .addComponent(btnLatte, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMocca, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumber)
                    .addComponent(txtNumberCoffees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLatte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMocca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShortBlack)
                .addGap(18, 18, 18)
                .addComponent(btnCalculate)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatteActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_btnLatteActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
        if (btnLatte.isSelected()) {
            costCoffee = costLatte;
        }
        else if (btnMocca.isSelected()) {
            costCoffee = costMocca;
        }
        else if (btnShortBlack.isSelected()) {
            costCoffee = costShortBlack;
        }
        else { costCoffee = 0; }
        
        setTotalCost(costCoffee*getNumberOfCoffees());
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCostActionPerformed

    private void txtNumberCoffeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberCoffeesActionPerformed
        
        try {
            numberOfCoffees = Integer.parseInt(txtNumberCoffees.getText());
        } catch (Exception ex) {
            txtTotalCost.setText("Number of Coffees needs to be an Integer");
        }
    }//GEN-LAST:event_txtNumberCoffeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.ButtonGroup btnCoffees;
    private javax.swing.JRadioButton btnLatte;
    private javax.swing.JRadioButton btnMocca;
    private javax.swing.JRadioButton btnShortBlack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtNumberCoffees;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables

}
